author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/LionheartExtensions"
github_file_prefix: "https://github.com/lionheart/LionheartExtensions/tree/3.7.1"
xcodebuild_arguments: ["-workspace", "Example/LionheartExtensions.xcworkspace", "-scheme", "LionheartExtensions"]
readme: "README.md"
copyright: "&copy; 2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"

